bitfocus/companion-module-obs-studio

HELP.md, index.js, package.json
Tested running OBS on Mac (from Companion running on MacOS and Windows)
=> Add "Set Source Mute" Action.

HELP.md, index.js, package.json, yarn.lock
This pull request adds actions and feedback to preview scenes and to execute transitions. I would like to know a better way to handle [upgrading](https://github.com/bitfocus/companion-module-obs-studio/pull/4/files#diff-168726dbe96b3ce427e7fedce31bb0bcR461) as right now, without the condition undefined values makes the bank black on black instead of the default, until the button is clicked in the configuration UI and it is updated with the defaults.
=> Studio mode: preview scene/execute transition

index.js
This PR resolves #12 by adding a Scene option to to the Toggle Scene Item Visibility action. Very nice indeed.
=> Added Scene option to Toggle Scene Item Visibility action

HELP.md, index.js
This wonderful PR adds two actions, **Set Source Text (FreeType 2)** and **Set Source Text (GDI+)** that let a user change the text in a text source. I also fixed a typo :100: 
This closes #13 .
=> Add Set Source Text action

index.js
Fix for https://github.com/bitfocus/companion-module-obs-studio/issues/17
=> Fix item visbility canceling each other out

index.js
Adjusted to proper naming to fix https://github.com/bitfocus/companion-module-obs-studio/issues/23
=> Fix TypeError

index.js
Added support for the ToggleMute action
=> Adding ToggleMute to obs

index.js, package.json
Cannot read property 'forEach' of undefined
=> Bugfix TypeError

index.js
lets see if this one works better
=> Added seperate buttons for Start / Stop on Recording and Streaming - v2

index.js
I found these variables to be useful.
=> Add more variables from OBS

index.js
Adds real toggling for source visibility and makes inputs a dropdown for easier use.
Fixes #36, #22.
=> Add real toggle for source visibility

index.js
Add actions and feedback for Profiles and Scene Collections.
=> Support Profile and Scene Collections

index.js
Add a different feedback check that looks for a source to be visible inside a specific scene.
=> Add feedback if a source in a scene is enabled

index.js
There are race conditions inside OBS that cause OBS to crash when refreshing
source lists while scene collection loading is happening.
This prevents those issues.
=> Perform less reloading on source destroy

HELP.md
Closes https://github.com/bitfocus/companion-module-obs-studio/issues/50
Closes https://github.com/bitfocus/companion-module-obs-studio/issues/33
=> Add help guide for Hotkey ID function

index.js
Fixes https://github.com/bitfocus/companion-module-obs-studio/issues/62
=> Add default transition behavior

index.js
Adds the ability to start/ stop various outputs
Closes https://github.com/bitfocus/companion-module-obs-studio/issues/59
Closes https://github.com/bitfocus/companion-module-obs-studio/issues/49
=> Feat: Start/stop outputs

index.js
Fixes https://github.com/bitfocus/companion-module-obs-studio/issues/60
=> Fix authentication failure loop

index.js
–Adds a start and stop action for outputs 
–Adds feedback for active outputs
Closes https://github.com/bitfocus/companion-module-obs-studio/issues/69
=> Feat: Start/Stop Output action, output feedback

index.js
Hopefully reduce issues reports related to not using recent plugin version
=> Minor: Warn user about out of date websocket version

index.js
Closes https://github.com/bitfocus/companion-module-obs-studio/issues/35
=> Feat: Add "Set Stream Settings" action

HELP.md, index.js
Closes https://github.com/bitfocus/companion-module-obs-studio/issues/70
=> Feat: Add smart switcher action

index.js
Closes https://github.com/bitfocus/companion-module-obs-studio/issues/53
=> Feat: Add set volume action

index.js
Fixes https://github.com/bitfocus/companion-module-obs-studio/issues/65
Fixes https://github.com/bitfocus/companion-module-obs-studio/issues/78
Fixes https://github.com/bitfocus/companion-module-obs-studio/issues/79
=> Fix: Correct toggling and feedback for grouped sources, nested scenes, sources in multiple scenes

index.js
Partially fulfills #84 
Actions
-  Set Transition Duration
- Refresh Browser Source
- Set Audio Monitor Type
- Take Screenshot
Variables
- Recording File Name
- Current Transition
- Recording Timecode
Feedback
- Transition Active
- Current Transition
=> Add new actions, feedbacks, variables

index.js
- Add feedback for paused recording state (partially fulfills new requests in https://github.com/bitfocus/companion-module-obs-studio/issues/84)
- Update recording state variable to be more descriptive (Recording, Stopped, Paused) (partially fulfills new requests in https://github.com/bitfocus/companion-module-obs-studio/issues/84)
- Give recording variables default states on start-up
- Move all recording related checks to the same function instead of being spread across multiple
- Add transition duration variable / feedback (partially fulfills new requests in https://github.com/bitfocus/companion-module-obs-studio/issues/84)
- Minor clean-up stream starting, feedback color defaults
=> Minor: Add recording paused state to variable / feedback, add transition duration variable / feedback

index.js
Closes https://github.com/bitfocus/companion-module-obs-studio/issues/51
=> Feat: Toggle filter action, filter enabled feedback

HELP.md, index.js, package.json
- Upgrade to boolean for most feedbacks
- Add all scenes to source list ( https://github.com/bitfocus/companion-module-obs-studio/issues/84#issuecomment-859725706)
- Allow preview scene as an option (fixes https://github.com/bitfocus/companion-module-obs-studio/issues/99)
- Add quick transition action (fixes https://github.com/bitfocus/companion-module-obs-studio/issues/89)
- More accurate version checking of obs-websocket
- Cleanup and standardize action/feedback names, descriptions, and help document
- Make streaming, timecode, cpu, memory, and desk space  variables more legible
- Fix issue where TCP socket was left open
- Added presets for outputs, transitions, record info, and streaming info
=> Upgrade to boolean feedbacks, add quick transition action, add more scenes as sources, cleanup help docs

HELP.md, index.js, package.json
New actions:
- Adjust Volume
- Play / Pause Media
- Restart Media
- Stop Media
- Next Media
- Previous Media
- Set Media Time
- Scrub Media
New feedbacks:
- Audio Muted (closes https://github.com/bitfocus/companion-module-obs-studio/issues/18)
- Audio Monitor Type (closes https://github.com/bitfocus/companion-module-obs-studio/issues/84)
- Media Playing (closes https://github.com/bitfocus/companion-module-obs-studio/issues/72)
- Source in Preview Scene (closes https://github.com/bitfocus/companion-module-obs-studio/issues/58)
New variables:
- Media status
- Current text (closes https://github.com/bitfocus/companion-module-obs-studio/issues/72#issuecomment-812874857)
New Presets:
-  Source status (preview/program)
- Media Source toggle
=> Feat: Audio feedbacks, previewed source feedbacks, media actions / feedbacks / presets /variables

HELP.md, index.js, package.json
Closes https://github.com/bitfocus/companion-module-obs-studio/issues/108
=> Minor: Media source file name variable

.gitignore, HELP.md, index.js, package.json, yarn.lock
Feat:
- Add volume feedback and variable closes https://github.com/bitfocus/companion-module-obs-studio/issues/110
Minor:
- Update to latest obs-websocket-js version
Fix:
- Separate initial media list creation from update function (closes https://github.com/bitfocus/companion-module-obs-studio/issues/112)
- Check for file path updates on SceneItem change instead of only on play
- Rate limiter on SceneItem changes to prevent overload
- Remove media source update from MediaStarted to prevent media sources being undefined (fixes https://github.com/bitfocus/companion-module-obs-studio/issues/114)
=> Feat: add volume feedbacks and variables, update obs-websocket-js version

index.js
Resloves https://github.com/bitfocus/companion-module-obs-studio/issues/131
=> Allow variables for Source Properties

HELP.md, index.js, package.json
https://github.com/bitfocus/companion-module-obs-studio/issues/42#issuecomment-1030307156
=> Feat: Add custom command option

index.js
This feature implements separate feedbacks for scene in program and and scene in preview.
=> Feat: Separate program and preview feedbacks for scene_active

HELP.md, index.js
This feature adds "all sources" to the "Set Source Visibility" action
.
=> Feat: All sources for toggle_scene_item action

HELP.md, README.md, actions.js, feedbacks.js, index.js, package.json
Fixes
- Prevent issue when using more than one instance of the OBS module
- Add filters from scenes, not just sources
=> Fix: Multiple instances, scene filters

README.md, index.js, package.json
Fixes https://github.com/bitfocus/companion-module-obs-studio/issues/185
=> Fix: Update choices for all text sources

actions.js
Fixes https://github.com/bitfocus/companion-module-obs-studio/issues/192
=> Fix: expose replay buffer action

actions.js
Closes https://github.com/bitfocus/companion-module-obs-studio/issues/200
=> Fix: Correct typo for Preview Scene action

companion/HELP.md, feedbacks.js, index.js
Closes https://github.com/bitfocus/companion-module-obs-studio/issues/203
=> Feat: Studio Mode feedback

companion/HELP.md, index.js, variables.js
Fixes https://github.com/bitfocus/companion-module-obs-studio/issues/210
=> Fix: restore kbps variable

actions.js
Resolves https://github.com/bitfocus/companion-module-obs-studio/issues/221
=> Fix: unable to run custom command

actions.js, index.js
Closes https://github.com/bitfocus/companion-module-obs-studio/issues/228
=> feat: preview next/ previous scene

feedbacks.js, index.js
Closes https://github.com/bitfocus/companion-module-obs-studio/issues/220
=> feat: support for vendorEvent feedbacks

actions.js
Closes https://github.com/bitfocus/companion-module-obs-studio/issues/233
=> feat: adjust source volume by percentage

actions.js, index.js, variables.js
Resolves https://github.com/bitfocus/companion-module-obs-studio/issues/237 & https://github.com/bitfocus/companion-module-obs-studio/issues/249
=> fix: use new inputSettings event for proper updates

companion/HELP.md, feedbacks.js, index.js, presets.js, variables.js
Closes https://github.com/bitfocus/companion-module-obs-studio/issues/251
=> feat: Disk Space Remaining feedback, variable updates

feedbacks.js
Fixes https://github.com/bitfocus/companion-module-obs-studio/issues/239#issuecomment-2159123255
=> fix: ensure feedbacks are rechecked if vars change

README.md, actions.js, index.js, package.json, variables.js, yarn.lock
Closes https://github.com/bitfocus/companion-module-obs-studio/issues/284
=> feat: save custom command response to variable

README.md, index.js, package.json, yarn.lock
Closes https://github.com/bitfocus/companion-module-obs-studio/issues/294
=> fix: cleanup listeners

README.md, actions.js, companion/HELP.md, index.js, package.json, yarn.lock
- All actions now support sequential execution _(requires Companion 3.5)_
- Fix
- Current Media variables showing info from media that is playing, but not in program
- Current Media variables disappearing when media is paused, but still in program
- Quick Transition not working after being used once in some instances
=> fix: current media variable improvements

index.js, package.json, yarn.lock
Closes https://github.com/bitfocus/companion-module-obs-studio/issues/309
=> fix: scene filters not appearing in dropdown
